version: "3.8"

services:
  
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
      - $PWD/wordpress/wp-content/themes:/var/www/html/wp-content/themes
    ports:
      - 80:80
    expose: 
      - 80
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - database
    networks:
      - wp-network

  database:
    image: mysql:latest
    container_name: database
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD='12345'
    depends_on:
      - database
    networks:
      - wp-network

networks:
  wp-network:

volumes:
  wp_data:
  db_data: