version: '2'

services:

   database:
     image: mysql
     volumes:
       - ./database:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - database
     image: wordpress
     ports:
       - "8000:80"
     restart: always
     volumes:
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes
     environment:
       WORDPRESS_DB_HOST: database:3306
       WORDPRESS_DB_PASSWORD: wordpress